name: Chromatic Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  run-chromatic:
    name: Chromatic Visual Regression
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List contents of nuxt-app directory
        run: ls -al ./nuxt-app

      - name: Install dependencies
        run: npm install
        working-directory: ./nuxt-app

      - name: Publish to Chromatic
        run: npm run chromatic -- --auto-accept-changesz
        working-directory: ./nuxt-app
